# Generated by Django 5.0.6 on 2024-08-02 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0003_rename_name_availabledates_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dose',
            old_name='hospital_name',
            new_name='vaccine_center',
        ),
    ]
