# Generated by Django 5.0.6 on 2024-08-03 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0004_rename_hospital_name_dose_vaccine_center'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dose',
            name='date',
        ),
        migrations.RemoveField(
            model_name='dose',
            name='dose_number',
        ),
        migrations.AddField(
            model_name='dose',
            name='firstDose_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_doses', to='vaccine.availabledates'),
        ),
        migrations.AddField(
            model_name='dose',
            name='secondDose_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_doses', to='vaccine.availabledates'),
        ),
    ]
