# Generated by Django 5.0.6 on 2024-08-08 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0006_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dose',
            name='cancel',
        ),
    ]
