# Generated by Django 5.0.6 on 2024-07-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_vaccine_batch_number_vaccine_expiry_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccineschedule',
            old_name='date',
            new_name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='vaccineschedule',
            name='notes',
        ),
        migrations.AddField(
            model_name='vaccine',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='doctor/images/'),
        ),
        migrations.AddField(
            model_name='vaccineschedule',
            name='patient_name',
            field=models.CharField(default='anything', max_length=100),
        ),
    ]
