# Generated by Django 5.0.6 on 2024-07-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_rename_date_vaccineschedule_scheduled_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccineschedule',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='vaccineschedule',
            name='vaccine',
        ),
    ]
