# Generated by Django 5.0.6 on 2024-07-28 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_remove_vaccineschedule_doctor_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VaccineSchedule',
        ),
    ]
