# Generated by Django 5.0.6 on 2024-08-08 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_delete_vaccineschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='age_limit',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
