# Generated by Django 5.0.6 on 2024-08-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_vaccine_age_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='vaccine-images'),
        ),
    ]
