# Generated by Django 5.0.6 on 2024-08-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0008_alter_vaccine_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='image',
            field=models.URLField(),
        ),
    ]
